spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expensebee
    username: expensebee
    password: expensebee
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
