spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/expensebee
    username: expensebee
    password: expensebee
  jpa:
    hibernate:
      ddl-auto: update
api:
  security:
    token:
      secret: ${JWT_SECRET:batatadoce}
