#!/bin/bash

commit_msg_file="$1"

commit_msg=$(cat "$commit_msg_file")

regex="^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert|remove): .{1,100}$"

if ! [[ $commit_msg =~ $regex ]]; then
    echo "Commit message does not match the required format:"
    echo "  <type>: <description>"
    echo "Types: feat, fix, docs, style, refactor, perf, test, chore, build, ci, revert"
    echo "Description should be 1- 100 characters."
    exit 1
fi
