INSERT INTO tb_roles (role_id, created_at, name, updated_at)
VALUES
  (1, CURRENT_TIMESTAMP, 'ADMIN', CURRENT_TIMESTAMP),
  (2, CURRENT_TIMESTAMP, 'USER', CURRENT_TIMESTAMP),
  (3, CURRENT_TIMESTAMP, 'DEV', CURRENT_TIMESTAMP);
